from .models import LoginResult, OnlineUserInfo

class XtuNetwork:
    def __init__(self, username: int, password: str): ...
    async def __aenter__(self) -> "XtuNetwork": ...
    async def __aexit__(self, exc_type, exc_val, exc_tb): ...
    async def aclose(self) -> None: ...
    async def login(self) -> "LoginResult": ...
    async def getUserIndex(self) -> str: ...
    async def getQueryString(self) -> str: ...
    async def logout(self) -> None: ...
    async def getOnlineUserInfo(self) -> "OnlineUserInfo" | dict: ...
    async def checkOnline(self) -> bool: ...
    async def checkNetwork(self) -> bool: ...
    async def getErrorMsg(self) -> str: ...
